### ISSUE TITLE
Emojis downloaded with ":" characters will throw an OS Errorno 22

### ISSUE THREAD

**Issue by J-DannyMartinez** [Firenza/ExportImportSlackEmoji#3]
Hello friend,

This is my first GitHub post, and I am in no way proficient with Python so please take this with a grain of salt :) 

**Expected Outcome:** Emojis will download with no errors.
**Actual Outcome:** `OS Errorno22` error when downloading emoji with the name _:movember:_
**Reason for error:** Windows will not accept any file names containing the character ":"
**My fix for the issue:** Added `emojiName = emojiName.replace(':','_')` to run right before the emoji is written to the file (line 57)

-----

Currently, any custom emojis with the ":" character in their name will throw an OS errorno 22 due to not being a valid file name for Windows, as shown in the image below when attempting a download on the emoji "_:movember:_".

I added a line to replace any ":" characters in emojiFileName to "_" which has resolved the issue. Perhaps there is a more elegant way to check this?

-----

![image](https://user-images.githubusercontent.com/14081018/92332826-5f3d3080-f035-11ea-83ef-a7a2b9ba98cd.png)

-----

Hope this helps!

**Comment by Firenza** [comment]
Hey good idea, feel free to submit a pull request and I'll merge it :)

**Comment by Firenza** [comment]
Actually I just created the PR myself with a regex so it's easily expandable for other characters https://github.com/Firenza/ExportImportSlackEmoji/pull/4.  I'll get the merged after I verify it works

**Comment by J-DannyMartinez** [comment]
Excellent! I am actually brand new to this world and wasn't sure what a pull request was before a quick google search. Thank you for shepherding my idea, and I'm glad my first post had a positive impact!

**Comment by Firenza** [comment]
Well welcome to this world 😄  Yes thank you for your feedback, the changes are in!
